swagger: "2.0"
info:
  description: "REST-API documentation for optimise"
  version: "1.0.0"
  title: "Optimise REST-API"
  contact:
    email: "c.sou16@imperial.ac.uk"
host: "localhost:3000"
basePath: "/"
paths:
  /users/login:
    post:
      summary: 'User login'
  /users/logout:
    post:
      summary: 'User logout'
  /users:
    post:
      summary: 'create a new user (admin only)'
    put:
      summary: "change a user's password (self only)"
    delete:
      summary: "delete a user (admin only)"
    get:
      summary: 'get the list of all users (admin only)'
  /patients:
    get:
      summary: 'search patient'
      description: 'if query string is not provided, then it returns all the patients. if query string "id={id}" is provided, then it returns patients with id containing "id"'
      produces: 
      - "application/json"
      responses:
        400:
          description: 'The query string can only have one parameter "id"'
        200:
          description: 'Result'
    post:
      summary: 'create a patient'
    delete:
      summary: 'delete a patient (admin only)'
  /patientProfile/:id:
    get:
      summary: 'get patient information by id'
      description: 'get patient information by id'
      produces: 
      - "application/json"
      responses:
        200:
          description: 'Result. Could be empty'
  /visit:
    get:
      summary: 'get all visits of a certain patient'
    post:
      summary: 'create a visit'
    delete:
      summary: 'delete a visit'
  