version: "3"
services:
  application:
    image: datascienceinstitute/optimise
    links:
      - database
    depends_on:
      - database
    restart: on-failure
    ports:
      - "8080:80"
    networks:
      - internal
  mongo:
    image: mongo
    volumes:
      - ./runtime/mongo:/var/lib/mongodb
    restart: always
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    networks:
      - internal
networks:
  internal:
    driver_opts:
      internal: "true"
    driver: bridge      
  shared:
    driver_opts:
      enable_ipv6: "true"
    driver: bridge
    ipam:
     config:
       - subnet: 172.55.0.0/16
         gateway: 172.55.0.1
