import EditVisitHandler from './editVisit';
import EditTestHandler from './editTest';
import EditCEHandler from './editClinicalEvent';
import EditMedHandler from './editMedication';
import EditDemoHandler from './editDemographic';
import EditPregnanciesHandler from './editPregnancy';
import EditPrimaryDiagnosesHandler from './editPrimaryDiagnosis';
import EditCommunicationHandler from './editCommunication';
import EditPerformanceMesaureHandler from './editEdss';
import AddComorbidityHandler from './addComorbidity';

export const EditVisit = EditVisitHandler;
export const AddComorbidity = AddComorbidityHandler;
export const EditTest = EditTestHandler;
export const EditCE = EditCEHandler;
export const EditMed = EditMedHandler;
export const EditDemo = EditDemoHandler;
export const EditPregnancies = EditPregnanciesHandler;
export const EditDiagnoses = EditPrimaryDiagnosesHandler;
export const EditCommunication = EditCommunicationHandler;
export const EditPerformanceMesaure = EditPerformanceMesaureHandler;