const availableFields = {
    visitFields: [
        {
            id: 1,
            definition: 'Systolic Blood Pressure',
            idname: 'visit_systolic_blood_pressure',
            section: 1,
            subsection: null,
            type: 2,
            unit: 'mmHg',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1
        },
        {
            id: 2,
            definition: 'Heart Rate',
            idname: 'visit_heart_rate',
            section: 1,
            subsection: null,
            type: 2,
            unit: 'bpm',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1
        },
        {
            id: 3,
            definition: 'Diastolic Blood Pressure',
            idname: 'visit_diastolic_blood_pressure',
            section: 1,
            subsection: null,
            type: 2,
            unit: 'mmHg',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1
        },
        {
            id: 4,
            definition: 'Height',
            idname: 'visit_height',
            section: 1,
            subsection: null,
            type: 2,
            unit: 'cm',
            module: 'MS',
            permittedValues: '> 0, int',
            labels: null,
            referenceType: 1
        },
        {
            id: 5,
            definition: 'Weight',
            idname: 'visit_weight',
            section: 1,
            subsection: null,
            type: 2,
            unit: 'kg',
            module: 'MS',
            permittedValues: '> 0, int',
            labels: null,
            referenceType: 1
        },
        {
            id: 6,
            definition: 'Percent School Attendance',
            idname: 'Percent_school_attendance',
            section: 1,
            subsection: null,
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '91-100,71-90,51-70,0-50,Unknown,NA',
            labels: null,
            referenceType: 1
        },
        {
            id: 7,
            definition: 'Higher function problem: cognitive problems',
            idname: 'Higher_function_problem:_cognitive_problems',
            section: 2,
            subsection: 'Cognitive Functions',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 8,
            definition: 'Higher function problem: emotional lability',
            idname: 'Higher_function_problem:_emotional_lability',
            section: 2,
            subsection: 'Cognitive Functions',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 9,
            definition: 'Higher function problem: depression',
            idname: 'Higher_function_problem:_depression',
            section: 2,
            subsection: 'Cognitive Functions',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 10,
            definition: 'Higher function problem: fatigue',
            idname: 'Higher_function_problem:_fatigue',
            section: 2,
            subsection: 'Cognitive Functions',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 11,
            definition: 'Higher function problem: seizure',
            idname: 'Higher_function_problem:_seizure',
            section: 2,
            subsection: 'Cognitive Functions',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 12,
            definition: 'Cranial nerves: oscillopsia',
            idname: 'Cranial_nerves:_oscillopsia',
            section: 2,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 13,
            definition: 'Cranial nerves: vertigo',
            idname: 'Cranial_nerves:_vertigo',
            section: 2,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 14,
            definition: 'Cranial nerves: blurred vision',
            idname: 'Cranial_nerves:_blurred_vision',
            section: 2,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 15,
            definition: 'Cranial nerves: double vision',
            idname: 'Cranial_nerves:_double_vision',
            section: 2,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 16,
            definition: 'Cranial nerves: uncontrolled eye movements',
            idname: 'Cranial_nerves:_uncontrolled_eye_movements',
            section: 2,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 17,
            definition: 'Cranial nerves: dysphagia',
            idname: 'Cranial_nerves:_dysphagia',
            section: 2,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 18,
            definition: 'Cranial nerves: facial weakness',
            idname: 'Cranial_nerves:_facial_weakness',
            section: 2,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 19,
            definition: 'Cranial nerves: greying of vision in one eye',
            idname: 'Cranial_nerves:_greying_of_vision_in_one_eye',
            section: 2,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1
        },
        {
            id: 20,
            definition: 'Cranial nerves: blindness in one eye',
            idname: 'Cranial_nerves:_blindness_in_one_eye',
            section: 2,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1
        },
        {
            id: 21,
            definition: 'Cranial nerves: facial pain',
            idname: 'Cranial_nerves:_facial_pain',
            section: 2,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1
        },
        {
            id: 22,
            definition: 'Cranial nerves: field defect / scotoma',
            idname: 'Cranial_nerves:_field_defect_/_scotoma',
            section: 2,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1
        },
        {
            id: 23,
            definition: 'Cranial nerves: facial hypoesthesia',
            idname: 'Cranial_nerves:_facial_hypoesthesia',
            section: 2,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1
        },
        {
            id: 24,
            definition: 'Motor: difficulty walking',
            idname: 'Motor:_difficulty_walking',
            section: 2,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 25,
            definition: 'Motor: weakness upper limbs',
            idname: 'Motor:_weakness_upper_limbs',
            section: 2,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1
        },
        {
            id: 26,
            definition: 'Motor: weakness lower limbs',
            idname: 'Motor:_weakness_lower_limbs',
            section: 2,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1
        },
        {
            id: 27,
            definition: 'Motor: weakness lower limbs',
            idname: 'Motor:_weakness_lower_limbs',
            section: 2,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1
        },
        {
            id: 28,
            definition: 'Somatosensory: Lhermitte\'s sign',
            idname: 'Somatosensory:_Lhermitte\'s_sign',
            section: 2,
            subsection: 'Somatosensory',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 29,
            definition: 'Somatosensory: Heat intolerance',
            idname: 'Somatosensory:_Heat_intolerance',
            section: 2,
            subsection: 'Somatosensory',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 30,
            definition: 'Somatosensory: pain',
            idname: 'Somatosensory:_pain',
            section: 2,
            subsection: 'Somatosensory',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1
        },
        {
            id: 31,
            definition: 'Somatosensory: paresthesia',
            idname: 'Somatosensory:_paresthesia',
            section: 2,
            subsection: 'Somatosensory',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1
        },
        {
            id: 32,
            definition: 'Somatosensory: dysesthesia',
            idname: 'Somatosensory:_dysesthesia',
            section: 2,
            subsection: 'Somatosensory',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1
        },
        {
            id: 33,
            definition: 'Somatosensory: anesthesia',
            idname: 'Somatosensory:_anesthesia',
            section: 2,
            subsection: 'Somatosensory',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1
        },
        {
            id: 34,
            definition: 'Somatosensory: pruritus',
            idname: 'Somatosensory:_pruritus',
            section: 2,
            subsection: 'Somatosensory',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1
        },
        {
            id: 35,
            definition: 'Somatosensory: pain',
            idname: 'Somatosensory:_pain',
            section: 2,
            subsection: 'Somatosensory',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1
        },
        {
            id: 36,
            definition: 'Somatosensory: paresthesia',
            idname: 'Somatosensory:_paresthesia',
            section: 2,
            subsection: 'Somatosensory',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1
        },
        {
            id: 37,
            definition: 'Somatosensory: dysesthesia',
            idname: 'Somatosensory:_dysesthesia',
            section: 2,
            subsection: 'Somatosensory',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1
        },
        {
            id: 38,
            definition: 'Somatosensory: anesthesia',
            idname: 'Somatosensory:_anesthesia',
            section: 2,
            subsection: 'Somatosensory',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1
        },
        {
            id: 39,
            definition: 'Somatosensory: pruritus',
            idname: 'Somatosensory:_pruritus',
            section: 2,
            subsection: 'Somatosensory',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1
        },
        {
            id: 40,
            definition: 'Autonomic: bladder urgency',
            idname: 'Autonomic:_bladder_urgency',
            section: 2,
            subsection: 'Autonomic',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 41,
            definition: 'Autonomic: bladder frequency',
            idname: 'Autonomic:_bladder_frequency',
            section: 2,
            subsection: 'Autonomic',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 42,
            definition: 'Autonomic: bladder incontinence',
            idname: 'Autonomic:_bladder_incontinence',
            section: 2,
            subsection: 'Autonomic',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 43,
            definition: 'Autonomic: bladder hesitancy',
            idname: 'Autonomic:_bladder_hesitancy',
            section: 2,
            subsection: 'Autonomic',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 44,
            definition: 'Autonomic: constipation',
            idname: 'Autonomic:_constipation',
            section: 2,
            subsection: 'Autonomic',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 45,
            definition: 'Autonomic: bowel incontinence',
            idname: 'Autonomic:_bowel_incontinence',
            section: 2,
            subsection: 'Autonomic',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 46,
            definition: 'Autonomic: problems with sexual function',
            idname: 'Autonomic:_problems_with_sexual_function',
            section: 2,
            subsection: 'Autonomic',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 47,
            definition: 'Higher function problem: information processing speed',
            idname: 'Higher_function_problem:_information_processing_speed',
            section: 3,
            subsection: 'Cognitive Functions',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 48,
            definition: 'Higher function problem: executive functions',
            idname: 'Higher_function_problem:_executive_functions',
            section: 3,
            subsection: 'Cognitive Functions',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 49,
            definition: 'Higher function problem: memory',
            idname: 'Higher_function_problem:_memory',
            section: 3,
            subsection: 'Cognitive Functions',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 50,
            definition: 'Higher function problem: verbal fluency',
            idname: 'Higher_function_problem:_verbal_fluency',
            section: 3,
            subsection: 'Cognitive Functions',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 51,
            definition: 'Higher function problem: seizure',
            idname: 'Higher_function_problem:_seizure',
            section: 3,
            subsection: 'Cognitive Functions',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 52,
            definition: 'Cranial nerves: nystagmus',
            idname: 'Cranial_nerves:_nystagmus',
            section: 3,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 53,
            definition: 'Cranial nerves: red desaturation',
            idname: 'Cranial_nerves:_red_desaturation',
            section: 3,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1
        },
        {
            id: 54,
            definition: 'Cranial nerves: sixth nerve palsy',
            idname: 'Cranial_nerves:_sixth_nerve_palsy',
            section: 3,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1
        },
        {
            id: 55,
            definition: 'Cranial nerves: third nerve palsy',
            idname: 'Cranial_nerves:_third_nerve_palsy',
            section: 3,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1
        },
        {
            id: 56,
            definition: 'Cranial nerves: trigeminal neuralgia',
            idname: 'Cranial_nerves:_trigeminal_neuralgia',
            section: 3,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1
        },
        {
            id: 57,
            definition: 'Cranial nerves: trigeninal palsy',
            idname: 'Cranial_nerves:_trigeninal_palsy',
            section: 3,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1
        },
        {
            id: 58,
            definition: 'Cranial nerves: fourth nerve palsy',
            idname: 'Cranial_nerves:_fourth_nerve_palsy',
            section: 3,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1
        },
        {
            id: 59,
            definition: 'Cranial nerves: facial hypoesthesia',
            idname: 'Cranial_nerves:_facial_hypoesthesia',
            section: 3,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1
        },
        {
            id: 60,
            definition: 'Cranial nerves: hearing loss',
            idname: 'Cranial_nerves:_hearing_loss',
            section: 3,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1
        },
        {
            id: 61,
            definition: 'Motor: tremor postural upper limbs',
            idname: 'Motor:_tremor_postural_upper_limbs',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1
        },
        {
            id: 62,
            definition: 'Motor: tremor intention upper limbs',
            idname: 'Motor:_tremor_intention_upper_limbs',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1
        },
        {
            id: 63,
            definition: 'Motor: spasticity upper limbs',
            idname: 'Motor:_spasticity_upper_limbs',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1
        },
        {
            id: 64,
            definition: 'Motor: spasticity lower limbs',
            idname: 'Motor:_spasticity_lower_limbs',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1
        },
        {
            id: 65,
            definition: 'Motor: tendon reflexes: hyperreflexia: biceps right',
            idname: 'Motor:_tendon_reflexes:_hyperreflexia:_biceps_right',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '3,4',
            labels: null,
            referenceType: 1
        },
        {
            id: 66,
            definition: 'Motor: tendon reflexes: hyperreflexia: biceps left',
            idname: 'Motor:_tendon_reflexes:_hyperreflexia:_biceps_left',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '3,4',
            labels: null,
            referenceType: 1
        },
        {
            id: 67,
            definition: 'Motor: tendon reflexes: hyperreflexia: patella right',
            idname: 'Motor:_tendon_reflexes:_hyperreflexia:_patella_right',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '3,4',
            labels: null,
            referenceType: 1
        },
        {
            id: 68,
            definition: 'Motor: tendon reflexes: hyperreflexia: patella left',
            idname: 'Motor:_tendon_reflexes:_hyperreflexia:_patella_left',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '3,4',
            labels: null,
            referenceType: 1
        },
        {
            id: 69,
            definition: 'Motor: tendon reflexes: hyperreflexia: ankle right',
            idname: 'Motor:_tendon_reflexes:_hyperreflexia:_ankle_right',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '3,4',
            labels: null,
            referenceType: 1
        },
        {
            id: 70,
            definition: 'Motor: tendon reflexes: hyperreflexia: ankle left',
            idname: 'Motor:_tendon_reflexes:_hyperreflexia:_ankle_left',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '3,4',
            labels: null,
            referenceType: 1
        },
        {
            id: 71,
            definition: 'Motor: tendon reflexes: hyporeflexia: biceps right',
            idname: 'Motor:_tendon_reflexes:_hyporeflexia:_biceps_right',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '1,2',
            labels: null,
            referenceType: 1
        },
        {
            id: 72,
            definition: 'Motor: tendon reflexes: hyporeflexia: biceps left',
            idname: 'Motor:_tendon_reflexes:_hyporeflexia:_biceps_left',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '1,2',
            labels: null,
            referenceType: 1
        },
        {
            id: 73,
            definition: 'Motor: tendon reflexes: hyporeflexia: patella right',
            idname: 'Motor:_tendon_reflexes:_hyporeflexia:_patella_right',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '1,2',
            labels: null,
            referenceType: 1
        },
        {
            id: 74,
            definition: 'Motor: tendon reflexes: hyporeflexia: patella left',
            idname: 'Motor:_tendon_reflexes:_hyporeflexia:_patella_left',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '1,2',
            labels: null,
            referenceType: 1
        },
        {
            id: 75,
            definition: 'Motor: tendon reflexes: hyporeflexia: ankle right',
            idname: 'Motor:_tendon_reflexes:_hyporeflexia:_ankle_right',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '1,2',
            labels: null,
            referenceType: 1
        },
        {
            id: 76,
            definition: 'Motor: tendon reflexes: hyporeflexia: ankle left',
            idname: 'Motor:_tendon_reflexes:_hyporeflexia:_ankle_left',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '1,2',
            labels: null,
            referenceType: 1
        },
        {
            id: 77,
            definition: 'Motor: tendon reflexes: plantar response right',
            idname: 'Motor:_tendon_reflexes:_plantar_response_right',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'NORMAL,ABNORMAL,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 78,
            definition: 'Motor: tendon reflexes: plantar response left',
            idname: 'Motor:_tendon_reflexes:_plantar_response_left',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'NORMAL,ABNORMAL,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 79,
            definition: 'Cerebellar: Ataxia upper limb',
            idname: 'Cerebellar:_Ataxia_upper_limb',
            section: 3,
            subsection: 'Cerebellar',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 80,
            definition: 'Cerebellar: Ataxia lower limb',
            idname: 'Cerebellar:_Ataxia_lower_limb',
            section: 3,
            subsection: 'Cerebellar',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 81,
            definition: 'Cerebellar: Ataxia trunk',
            idname: 'Cerebellar:_Ataxia_trunk',
            section: 3,
            subsection: 'Cerebellar',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 82,
            definition: 'Mobility: problem',
            idname: 'Mobility:_problem',
            section: 3,
            subsection: 'Mobility',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LIMITED AMBULATION,WHEELCHAIR BOUND,BEDRIDDEN,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 83,
            definition: 'Mobility: using walking aid',
            idname: 'Mobility:_using_walking_aid',
            section: 3,
            subsection: 'Mobility',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            labels: null,
            referenceType: 1
        },
        {
            id: 84,
            definition: 'Expanded Disability Status Scale (EDSS) Total',
            idname: 'Expanded_Disability_Status_Scale_EDSS_total',
            section: 4,
            subsection: 'EDSS',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: '0,1,2,3,4,5,6,7,8,9,10',
            labels: null,
            referenceType: 1
        },
        {
            id: 85,
            definition: 'Expanded Disability Status Scale (EDSS) Total Calculated',
            idname: 'Expanded_Disability_Status_Scale_EDSS_total_calculated',
            section: 4,
            subsection: 'EDSS',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: '0,1,2,3,4,5,6,7,8,9,10',
            labels: null,
            referenceType: 1
        },
        {
            id: 86,
            definition: 'Expanded Disability Status Scale (EDSS) Pyramidal',
            idname: 'Expanded_Disability_Status_Scale_EDSS_Pyramidal',
            section: 4,
            subsection: 'EDSS',
            type: 1,
            unit: null,
            module: 'MS',
            permittedValues: '0,1,2,3,4,5,6',
            labels: 'Normal,'
                + 'Abnormal signs without disability,'
                + 'Minimal disability,'
                + 'Mild or moderate paraparesis or hemiparesis (detectable weakness but most sustained for short periods, fatigue problem); severe monoparesis (almost no function),'
                + 'Marked paraparesis or hemiparesis (functions difficult); moderate quadriparesis (function decreased but can be sustained for short periods); or monoplegia,'
                + 'Paraplegia, hemiplegia or marked quadriparesis,'
                + 'Quadriplegia',
            referenceType: 1
        },
        {
            id: 87,
            definition: 'Expanded Disability Status Scale (EDSS) Cerebellar',
            idname: 'Expanded_Disability_Status_Scale_EDSS_Cerebellar',
            section: 4,
            subsection: 'EDSS',
            type: 1,
            unit: null,
            module: 'MS',
            permittedValues: '0,1,2,3,4,5',
            labels: 'Normal,'
                + 'Abnormal signs without disability,'
                + 'Mild ataxia,'
                + 'Moderate truncal or limb ataxia (tremor or clumsy movements interfere with function in all spheres),'
                + 'Severe ataxia in all limbs (most function is very difficult),'
                + 'Unable to perform coordinated movements due to ataxia',
            referenceType: 1
        },
        {
            id: 88,
            definition: 'Expanded Disability Status Scale (EDSS) Brain Stem',
            idname: 'Expanded_Disability_Status_Scale_EDSS_Brain_Stem',
            section: 4,
            subsection: 'EDSS',
            type: 1,
            unit: null,
            module: 'MS',
            permittedValues: '0,1,2,3,4,5',
            labels: 'Normal'
                + 'Signs only,'
                + 'Moderate nystagmus or other mild disability,'
                + 'Severe nystagmus, marked extraocular weakness or moderate disability of other cranial nerves,'
                + 'Marked dysarthria or other marked disability,'
                + 'Inability to swallow or speak',
            referenceType: 1
        },
        {
            id: 89,
            definition: 'Expanded Disability Status Scale (EDSS) Sensory',
            idname: 'Expanded_Disability_Status_Scale_EDSS_Sensory',
            section: 4,
            subsection: 'EDSS',
            type: 1,
            unit: null,
            module: 'MS',
            permittedValues: '0,1,2,3,4,5,6',
            labels: 'Normal,'
                + 'Vibration or figure-writing decreased, only in one or two limbs,'
                + 'Mild decrease in touch or pain or position sense, and/or moderate decrease in vibration in one or two limbs; or vibration decrease alone in three or four limbs,'
                + 'Moderate decrease in touch or pain or position sense, and/or essentially lost vibration in one or two limbs; or mild decrease in touch or pain and/or moderate decrease in all proprioceptive test in three or four limbs,'
                + 'Marked decrease in touch or pain or lost proprioception, alone or combined, in one or two limbs; or moderate decrease in touch or pain and/or severe proprioceptive decrease in more then two limbs,'
                + 'Lost of sensation in one or two limbs; or proprioception for most of the body below the head,'
                + 'Sensation essentially lost below the head',
            referenceType: 1
        },
        {
            id: 90,
            definition: 'Expanded Disability Status Scale (EDSS) Bowel Bladder',
            idname: 'Expanded_Disability_Status_Scale_EDSS_Bowel_Bladder',
            section: 4,
            subsection: 'EDSS',
            type: 1,
            unit: null,
            module: 'MS',
            permittedValues: '0,1,2,3,4,5,6',
            labels: 'Normal,'
                + 'Mild urinary hesitancy, urgency or retention,'
                + 'Moderate hesitancy, urgency, retention of bowel or bladder, or rare urinary incontinence (intermittent self-catheterisation, manual compression to evacuate bladder or finger evacuation or stool),'
                + 'Frequent urinary incontinence,'
                + 'In need of regular intermittent catheterisation (and constant use of measures to evacuate stools),'
                + 'In dwelling catheter,'
                + 'Loss of bowel and/or bladder function,',
            referenceType: 1
        },
        {
            id: 91,
            definition: 'Expanded Disability Status Scale (EDSS) Visual',
            idname: 'Expanded_Disability_Status_Scale_EDSS_Bowel_Visual',
            section: 4,
            subsection: 'EDSS',
            type: 1,
            unit: null,
            module: 'MS',
            permittedValues: '0,1,2,3,4,5,6',
            labels: 'Normal,'
                + 'Scotoma with visual acuity (corrected) better then 6/9,'
                + 'Worse eye with maximal visual acuity (corrected) of 6/9 to 6/12,'
                + 'Worse eye with maximal visual acuity (corrected) of 6/18 to 6/24,'
                + 'Worse eye with maximal visual acuity (corrected) of 6/36 to 6/60. Or grade three plus maximal acuity of better eye of 6/18 or less,'
                + 'Worse eye with maximal visual acuity (corrected) of 6/60. Or grade four plus maximal visual acuity of better eye of 6/18 or less,'
                + 'Grade 5 plus maximal visual acuity of better eye worse then 6/18',
            referenceType: 1
        },
        {
            id: 92,
            definition: 'Expanded Disability Status Scale (EDSS) Mental',
            idname: 'Expanded_Disability_Status_Scale_EDSS_Mental',
            section: 4,
            subsection: 'EDSS',
            type: 1,
            unit: null,
            module: 'MS',
            permittedValues: '0,1,2,3,4,5',
            labels: 'Normal,'
                + 'Mood alteration only- fatigue not intefering with daily activity (does not affect EDSS score,),'
                + 'Mild decrease in mentation- fatigue intefering with daily activity,'
                + 'Moderate decrease in mentation,'
                + 'Marked decrease in mentation (chronic brain syndrome - moderate),'
                + 'Dementia or chronic brain syndrome - severe or incompetent',
            referenceType: 1
        },
        {
            id: 93,
            definition: 'Expanded Disability Status Scale (EDSS) Ambulation',
            idname: 'Expanded_Disability_Status_Scale_EDSS_Ambulation',
            section: 4,
            subsection: 'EDSS',
            type: 1,
            unit: null,
            module: 'MS',
            permittedValues: '0,1,2,3,4,5,6,7,8,9,10,11,12',
            labels: 'Fully ambulatory,'
                + '500 m without aid/rest,'
                + '300 m without aid/rest,'
                + '200 m without aid/rest,'
                + '100 m without aid/rest,'
                + '100 m with unilateral assistance,'
                + '200 m with bilateral assistance,'
                + 'Essentially restricted to wheelchair (wheels self),'
                + 'Restricted to wheelchair (may need help in transfer),'
                + 'Essentially restricted to bed/chair,'
                + 'Restricted to bed much of day,'
                + 'Bed patient. Can communicate and eat,'
                + 'Helpless bed patient. Unable to communicate/eat/swallow',
            referenceType: 1
        },
        {
            id: 94,
            definition: 'EDMUS',
            idname: 'EDMUS',
            section: 4,
            subsection: 'EDMUS',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '0,1,2,3,4,5,6A,6B,7,8,9,10',
            labels: 'Normal findings on neurological examination.,'
                + 'No disability. Minimal signs on neurological examination.,'
                + 'Minimal and not ambulation-related disability. Able to run.,'
                + 'Unlimited walking distance (WD) without rest but unable to run; or a significant not ambulation-related disability.,'
                + 'Walks without aid. Limited WD but > 500 meters without rest.,'
                + 'Walks without aid. Limited WD- < 500 meters without rest.,'
                + 'Walks with permanent unilateral support. WD < 100 meters without rest.,'
                + 'Walks with permanent bilateral support. WD < 100 meters without rest.,'
                + 'Home restricted. A few steps with wall or furniture assistance. WD < 20 meters without rest.,'
                + 'Chair restricted. Unable to take a step. Some effective use of arms.,'
                + 'Bedridden and totally helpless.,'
                + 'Death due to MS.',
            referenceType: 1
        },
        {
            id: 95,
            definition: '25 feet walk test trial n°1',
            idname: '25_feet_walk_test_first_try',
            section: 4,
            subsection: '25feet',
            type: 2,
            unit: 'sec',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1
        },
        {
            id: 96,
            definition: '25 feet walk test trial n°2',
            idname: '25_feet_walk_test_second_try',
            section: 4,
            subsection: '25feet',
            type: 2,
            unit: 'sec',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1
        },
        {
            id: 97,
            definition: 'Nine hole peg test: left: trial n°1',
            idname: 'Nine_hole_peg_test:_left:_first_try',
            section: 4,
            subsection: '9hole',
            type: 2,
            unit: 'sec',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1
        },
        {
            id: 98,
            definition: 'Nine hole peg test: left: trial n°2',
            idname: 'Nine_hole_peg_test:_left:_second_try',
            section: 4,
            subsection: '9hole',
            type: 2,
            unit: 'sec',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1
        },
        {
            id: 99,
            definition: 'Nine hole peg test: right: trial n°1',
            idname: 'Nine_hole_peg_test:_right:_first_try',
            section: 4,
            subsection: '9hole',
            type: 2,
            unit: 'sec',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1
        },
        {
            id: 100,
            definition: 'Nine hole peg test: right: trial n°2',
            idname: 'Nine_hole_peg_test:_right:_second_try',
            section: 4,
            subsection: '9hole',
            type: 2,
            unit: 'sec',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1
        },
        {
            id: 101,
            definition: 'Low contrast letter acuity: left ',
            idname: 'Low_contrast_letter_acuity:_left_',
            section: 4,
            subsection: 'VisualAcuity',
            type: 2,
            unit: '/20',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1
        },
        {
            id: 102,
            definition: 'Low contrast letter acuity: right',
            idname: 'Low_contrast_letter_acuity:_right',
            section: 4,
            subsection: 'VisualAcuity',
            type: 2,
            unit: '/20',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1
        },
        {
            id: 103,
            definition: 'symbol digit modality test',
            idname: 'symbol_digit_modality_test',
            section: 4,
            subsection: 'VisualAcuity',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1
        }],
    testFields: [
        {
            id: 1,
            definition: 'ANA',
            idname: 'ANA',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 2,
            definition: 'ANCA',
            idname: 'ANCA',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 3,
            definition: 'Anti-cardiolipin',
            idname: 'Anti-cardiolipin',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 4,
            definition: 'Anti-DNA',
            idname: 'Anti-DNA',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 5,
            definition: 'Anti-HCV antibody',
            idname: 'Anti-HCV_antibody',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 6,
            definition: 'Anti-HIV antibody',
            idname: 'Anti-HIV_antibody',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 7,
            definition: 'Anti-LKM',
            idname: 'Anti-LKM',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 8,
            definition: 'Anti-mitochondrial',
            idname: 'Anti-mitochondrial',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 9,
            definition: 'Anti-parietal cell antibodies',
            idname: 'Anti-parietal_cell_antibodies',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 10,
            definition: 'Anti-Ro',
            idname: 'Anti-Ro',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 11,
            definition: 'Anti-smooth muscle',
            idname: 'Anti-smooth_muscle',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 12,
            definition: 'anti-transglutaminase',
            idname: 'anti-transglutaminase',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 13,
            definition: 'anti-varicella',
            idname: 'anti-varicella',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 14,
            definition: 'AQP4',
            idname: 'AQP4',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 15,
            definition: 'GlyR',
            idname: 'GlyR',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 16,
            definition: 'HBV surface antigen',
            idname: 'HBV_surface_antigen',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 17,
            definition: 'hepatitis A',
            idname: 'hepatitis_A',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 18,
            definition: 'hepatitis B',
            idname: 'hepatitis_B',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 19,
            definition: 'hepatitis C',
            idname: 'hepatitis_C',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 20,
            definition: 'Jo1',
            idname: 'Jo1',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 21,
            definition: 'LA',
            idname: 'LA',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 22,
            definition: 'LUPUS anti-coagulant',
            idname: 'LUPUS_anti-coagulant',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 23,
            definition: 'MOG',
            idname: 'MOG',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 24,
            definition: 'Neutralising Anti-IFN antibody',
            idname: 'Neutralising_Anti-IFN_antibody',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 25,
            definition: 'Neutralising Anti-natalizumab antibody',
            idname: 'Neutralising_Anti-natalizumab_antibody',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 26,
            definition: 'NMDAR',
            idname: 'NMDAR',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 27,
            definition: 'NMO IgG',
            idname: 'NMO_IgG',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 28,
            definition: 'Plasma anti-JC virus',
            idname: 'Plasma_anti-JC_virus',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 29,
            definition: 'RNP',
            idname: 'RNP',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 30,
            definition: 'Scl70',
            idname: 'Scl70',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 31,
            definition: 'SM',
            idname: 'SM',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 32,
            definition: 'ANA: Flagged',
            idname: 'ANA:_Flagged',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 33,
            definition: 'ANCA: Flagged',
            idname: 'ANCA:_Flagged',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 34,
            definition: 'Anti-cardiolipin: Flagged',
            idname: 'Anti-cardiolipin:_Flagged',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 35,
            definition: 'Anti-DNA: Flagged',
            idname: 'Anti-DNA:_Flagged',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 36,
            definition: 'Anti-HCV antibody: Flagged',
            idname: 'Anti-HCV_antibody:_Flagged',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 37,
            definition: 'Anti-HIV antibody: Flagged',
            idname: 'Anti-HIV_antibody:_Flagged',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 38,
            definition: 'Anti-LKM: Flagged',
            idname: 'Anti-LKM:_Flagged',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 39,
            definition: 'Anti-mitochondrial: Flagged',
            idname: 'Anti-mitochondrial:_Flagged',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 40,
            definition: 'Anti-parietal cell antibodies: Flagged',
            idname: 'Anti-parietal_cell_antibodies:_Flagged',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 41,
            definition: 'Anti-Ro: Flagged',
            idname: 'Anti-Ro:_Flagged',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 42,
            definition: 'Anti-smooth muscle: Flagged',
            idname: 'Anti-smooth_muscle:_Flagged',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 43,
            definition: 'Anti-transglutaminase: Flagged',
            idname: 'Anti-transglutaminase:_Flagged',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 44,
            definition: 'Anti-varicella: Flagged',
            idname: 'Anti-varicella:_Flagged',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 45,
            definition: 'AQP4: Flagged',
            idname: 'AQP4:_Flagged',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 46,
            definition: 'GlyR: Flagged',
            idname: 'GlyR:_Flagged',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 47,
            definition: 'HBV surface antigen: Flagged',
            idname: 'HBV_surface_antigen:_Flagged',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 48,
            definition: 'Hepatitis A: Flagged',
            idname: 'Hepatitis_A:_Flagged',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 49,
            definition: 'Hepatitis B: Flagged',
            idname: 'Hepatitis_B:_Flagged',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 50,
            definition: 'Hepatitis C: Flagged',
            idname: 'Hepatitis_C:_Flagged',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 51,
            definition: 'Jo1: Flagged',
            idname: 'Jo1:_Flagged',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 52,
            definition: 'LA: Flagged',
            idname: 'LA:_Flagged',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 53,
            definition: 'LUPUS anti-coagulant: Flagged',
            idname: 'LUPUS_anti-coagulant:_Flagged',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 54,
            definition: 'MOG: Flagged',
            idname: 'MOG:_Flagged',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 55,
            definition: 'Neutralising Anti-IFN antibody: Flagged',
            idname: 'Neutralising_Anti-IFN_antibody:_Flagged',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 56,
            definition: 'Neutralising Anti-natalizumab antibody: Flagged',
            idname: 'Neutralising_Anti-natalizumab_antibody:_Flagged',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 57,
            definition: 'NMDAR: Flagged',
            idname: 'NMDAR:_Flagged',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 58,
            definition: 'NMO IgG: Flagged',
            idname: 'NMO_IgG:_Flagged',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 59,
            definition: 'Plasma anti-JC virus: Flagged',
            idname: 'Plasma_anti-JC_virus:_Flagged',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 60,
            definition: 'RNP: Flagged',
            idname: 'RNP:_Flagged',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 61,
            definition: 'Scl70: Flagged',
            idname: 'Scl70:_Flagged',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 62,
            definition: 'SM: Flagged',
            idname: 'SM:_Flagged',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 63,
            definition: 'P100 Left: Abnormal',
            idname: 'P100_Left:_Abnormal',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 2
        },
        {
            id: 64,
            definition: 'P100 Left: amplitude',
            idname: 'P100_Left:_amplitude',
            type: 1,
            unit: 'uV',
            module: 'MS',
            permittedValues: null,
            referenceType: 2
        },
        {
            id: 65,
            definition: 'P100 Left: P100 latency',
            idname: 'P100_Left:_P100_latency',
            type: 1,
            unit: 'msec',
            module: 'MS',
            permittedValues: null,
            referenceType: 2
        },
        {
            id: 66,
            definition: 'P100 right: Abnormal',
            idname: 'P100_right:_Abnormal',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 2
        },
        {
            id: 67,
            definition: 'P100 right: amplitude',
            idname: 'P100_right:_amplitude',
            type: 1,
            unit: 'uV',
            module: 'MS',
            permittedValues: null,
            referenceType: 2
        },
        {
            id: 68,
            definition: 'P100 right: P100 latency',
            idname: 'P100_right:_P100_latency',
            type: 1,
            unit: 'msec',
            module: 'MS',
            permittedValues: null,
            referenceType: 2
        },
        {
            id: 69,
            definition: 'SEP left: upper extremity: abnormal',
            idname: 'SEP_left:_upper_extremity:_abnormal',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 2
        },
        {
            id: 70,
            definition: 'SEP left: lower extremity: abnormal',
            idname: 'SEP_left:_lower_extremity:_abnormal',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 2
        },
        {
            id: 71,
            definition: 'SEP right: upper extremity: abnormal',
            idname: 'SEP_right:_upper_extremity:_abnormal',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 2
        },
        {
            id: 72,
            definition: 'SEP right: lower extremity: abnormal',
            idname: 'SEP_right:_lower_extremity:_abnormal',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 2
        },
        {
            id: 73,
            definition: 'Session Name',
            idname: 'Session_Name',
            type: 4,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 3
        },
        {
            id: 74,
            definition: 'Scans',
            idname: 'Scans',
            type: 6,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 3
        },
        {
            id: 75,
            definition: 'scan type',
            idname: 'scan_type',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'T1,T2',
            referenceType: 3
        },
        {
            id: 76,
            definition: 'Morphology: region',
            idname: 'Morphology:_region',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'BRAIN,SPINE',
            referenceType: 3
        },
        {
            id: 77,
            definition: 'Morphology: T1 hypointense lesions',
            idname: 'Morphology:_T1_hypointense_lesions',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'NEGATIVE,POSITIVE,NOT REPORTED',
            referenceType: 3
        },
        {
            id: 78,
            definition: 'Morphology: T2 hypointense lesions count',
            idname: 'Morphology:_T2_hypointense_lesions_count',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 3
        },
        {
            id: 79,
            definition: 'Morphology: T2 hypointense lesions volume',
            idname: 'Morphology:_T2_hypointense_lesions_volume',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 3
        },
        {
            id: 80,
            definition: 'Morphology: Gd enhancing lesions',
            idname: 'Morphology:_Gd_enhancing_lesions',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'NONE,SINGLE,MULTIPLE,UNKNOWN',
            referenceType: 3
        },
        {
            id: 81,
            definition: 'Morphology: Gd enhancing lesions volume',
            idname: 'Morphology:_Gd_enhancing_lesions_volume',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 3
        },
        {
            id: 82,
            definition: 'Summary',
            idname: 'Summary',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues:
                'NORMAL,TRAUMATIC,ABNORMAL MS-TYPICAL,ABNORMAL MS-ATYPICAL',
            referenceType: 4
        },
        {
            id: 83,
            definition: 'Total-protein',
            idname: 'Total-protein',
            type: 2,
            unit: 'mg/L',
            module: 'MS',
            permittedValues: null,
            referenceType: 4
        },
        {
            id: 84,
            definition: 'Glucose',
            idname: 'Glucose',
            type: 2,
            unit: 'mg/L',
            module: 'MS',
            permittedValues: null,
            referenceType: 4
        },
        {
            id: 85,
            definition: 'Q Albumin',
            idname: 'Q_Albumin',
            type: 2,
            unit: 'mg/L',
            module: 'MS',
            permittedValues: null,
            referenceType: 4
        },
        {
            id: 86,
            definition: 'IgG',
            idname: 'IgG',
            type: 2,
            unit: 'mg/L',
            module: 'MS',
            permittedValues: null,
            referenceType: 4
        },
        {
            id: 87,
            definition: 'Albumin',
            idname: 'Albumin',
            type: 2,
            unit: 'mg/L',
            module: 'MS',
            permittedValues: null,
            referenceType: 4
        },
        {
            id: 88,
            definition: 'IgG index',
            idname: 'IgG_index',
            type: 2,
            unit: 'mg/L',
            module: 'MS',
            permittedValues: null,
            referenceType: 4
        },
        {
            id: 89,
            definition: 'WCC',
            idname: 'WCC',
            type: 2,
            unit: 'mg/L',
            module: 'MS',
            permittedValues: null,
            referenceType: 4
        },
        {
            id: 90,
            definition: 'Lymphocytes',
            idname: 'Lymphocytes',
            type: 2,
            unit: 'mg/L',
            module: 'MS',
            permittedValues: null,
            referenceType: 4
        },
        {
            id: 91,
            definition: 'Oligoclonal Bands in CSF',
            idname: 'Oligoclonal_Bands_in_CSF',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'TEST NOT DONE,NOT DETECTED,DETECTED,UNKNOWN',
            referenceType: 4
        },
        {
            id: 92,
            definition: 'ALT (Alanine Aminotransferase) Test',
            idname: 'ALT_Alanine_Aminotransferase_Test',
            type: 2,
            unit: 'Units/Liter',
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 93,
            definition: 'AST (Aspartate Aminotransferase) Test',
            idname: 'AST_Aspartate_Aminotransferase_Test',
            type: 2,
            unit: 'Units/Liter',
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 94,
            definition: 'GGT (Gamma-Glutamyl Transpeptidase) Test',
            idname: 'GGT_Gamma_Glutamyl_Transpeptidase_Test',
            type: 2,
            unit: 'Units/Liter',
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 95,
            definition: 'Total WBC',
            idname: 'Total_WBC',
            type: 2,
            unit: 'mcL',
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 96,
            definition: 'Bilirubin',
            idname: 'Bilirubin',
            type: 2,
            unit: 'mg/dL',
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        }
    ],
    ceFields: [
        {
            id: 1,
            definition: 'Functional system affected: Pyramidal Tract',
            idname: 'Functional_system_affected_pyramidal_tract',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            referenceType: 1
        },
        {
            id: 2,
            definition: 'Functional system affected: Cerebellum',
            idname: 'Functional_system_affected_cerebellum',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            referenceType: 1
        },
        {
            id: 3,
            definition: 'Functional system affected:Brain Stem',
            idname: 'Functional_system_affected_Brain_Stem',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            referenceType: 1
        },
        {
            id: 4,
            definition: 'Functional system affected: Sensory',
            idname: 'Functional_system_affected_Sensory',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            referenceType: 1
        },
        {
            id: 5,
            definition: 'Functional system affected: Bowel/Bladder',
            idname: 'Functional_system_affected_Bowel_Bladder',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            referenceType: 1
        },
        {
            id: 6,
            definition: 'Functional system affected: Visual',
            idname: 'Functional_system_affected_Visual',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            referenceType: 1
        },
        {
            id: 7,
            definition: 'Functional system affected: Cognition',
            idname: 'Functional_system_affected_Cognition',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'YES,NO,UNKNOWN',
            referenceType: 1
        },
        {
            id: 8,
            definition: 'Duration',
            idname: 'Duration',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 1
        },
        {
            id: 9,
            definition: 'Severity',
            idname: 'Severity',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'Mild,Moderate,Severe,Unknown',
            referenceType: 1
        },
        {
            id: 10,
            definition: 'Recovery',
            idname: 'Recovery',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'Complete,Partial,None,Unknown',
            referenceType: 1
        },
        {
            id: 11,
            definition: 'Impact on ADL',
            idname: 'Impact_On_ADL',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'Yes,No,Unknown',
            referenceType: 1
        },
        {
            id: 12,
            definition: 'Steroids use',
            idname: 'Steroids',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'Yes,No,Unknown',
            referenceType: 1
        },
        {
            id: 13,
            definition: 'Infection Classification',
            idname: 'Infection_Classification',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'UTI,Bronchitis,Sinusitis,Gastroenteritis,Tinea Infection,Sepsis,Bacterial,Viral,Abscess,Other,Unknown',
            referenceType: 2
        },
        {
            id: 14,
            definition: 'Date of onset',
            idname: 'Date_Of_Onset',
            type: 4,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 2
        },
        {
            id: 15,
            definition: 'Date of resolution',
            idname: 'Date_Of_Resolution',
            type: 4,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 2
        },
        {
            id: 16,
            definition: 'Date of hospitalisation',
            idname: 'Date_Of_Hospitalisation',
            type: 4,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 2
        },
        {
            id: 17,
            definition: 'Date of discharge',
            idname: 'Date_Of_Discharge',
            type: 4,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 2
        },
        {
            id: 18,
            definition: 'Comments- Elaboration',
            idname: 'Comments_Elaboration_Infection',
            type: 4,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 2
        },
        {
            id: 19,
            definition: 'Opportunistic Infection Classification',
            idname: 'Opportunistic_Infection_Classification',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: 'PML,Herpes Zoster,Herpes Simplex,Varicella,Viral Hepatitis,Bacterial infection- listeria,Other infection,Mycosis,Abscess,Other,Unknown',
            referenceType: 3
        },
        {
            id: 20,
            definition: 'Date of onset',
            idname: 'Date_Of_Onset_opportunistic',
            type: 4,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 3
        },
        {
            id: 21,
            definition: 'Date of resolution',
            idname: 'Date_Of_Resolution_opportunistic',
            type: 4,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 3
        },
        {
            id: 22,
            definition: 'Comments- Elaboration',
            idname: 'Comments_Elaboration_Opportunistic_Infection',
            type: 4,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 3
        },
        {
            id: 23,
            definition: 'Primary and underlying cause of death',
            idname: 'Primary_and_underlying_cause_of_death',
            type: 4,
            unit: null,
            module: 'MS',
            permittedValues: null,
            referenceType: 4
        }
    ]
};

module.exports = availableFields;
