const availableDrugs = [
    { name: 'Alemtuzumab (Lemtrada)', dose: '0', module: 'Disease Modifying' } ,
    { name: 'Avonex (Interferon beta-1a)', dose: '0', module: 'Disease Modifying' },
    { name: 'Azathioprine', dose: '0', module: 'Disease Modifying' },
    { name: 'Betaferon (Interferon beta-1b)', dose: '0', module: 'Disease Modifying' },
    { name: 'Cladribine (Mavenclad)', dose: '0', module: 'Disease Modifying' },
    { name: 'Cyclophosphamide', dose: '0', module: 'Disease Modifying' },
    { name: 'Daclizumab (Zinbryta)', dose: '0', module: 'Disease Modifying' },
    { name: 'Dimethyl fumarate (Tecfidera)', dose: '0', module: 'Disease Modifying' },
    { name: 'Extavia (beta interferon-1b)', dose: '0', module: 'Disease Modifying' },
    { name: 'Fingolimod (Gilenya)', dose: '0', module: 'Disease Modifying' },
    { name: 'Glatiramer acetate (Copaxone)', dose: '0', module: 'Disease Modifying' },
    { name: 'Methotrexate', dose: '0', module: 'Disease Modifying' },
    { name: 'Mitoxantrone', dose: '0', module: 'Disease Modifying' },
    { name: 'Natalizumab (Tysabri)', dose: '300', module: 'Disease Modifying' },
    { name: 'Ocrelizumab (Ocrevus)', dose: '0', module: 'Disease Modifying' },
    { name: 'Plegridy (peginterferon beta-1a)', dose: '0', module: 'Disease Modifying' },
    { name: 'Rebif (beta interferon-1a)', dose: '0', module: 'Disease Modifying' },
    { name: 'Teriflunomide (Aubagio)', dose: '0', module: 'Disease Modifying' },
    { name: 'Rituximab', dose: '0', module: 'Disease Modifying' },
    { name: 'DMF', dose: '0', module: 'Disease Modifying' },
    { name: 'Terflunomide', dose: '0', module: 'Disease Modifying' },
    { name: 'Brabio', dose: '0', module: 'Disease Modifying' },
    { name: '4-aminopyridine', dose: '0', module: 'Symptomatic' },
    { name: 'Corticosteroids', dose: '0', module: 'Symptomatic' },
    { name: 'Prednisone', dose: '0', module: 'Symptomatic' },
    { name: 'Amantadine', dose: '0', module: 'Symptomatic' },
    { name: 'Baclofen', dose: '0', module: 'Symptomatic' },
    { name: 'IV Methyl-prednisolone', dose: '0', module: 'Symptomatic' },
    { name: 'IVIG', dose: '0', module: 'Symptomatic' },
    { name: 'Plasma Exchange', dose: '0', module: 'Symptomatic' },
    { name: 'Mycophenolic Acid', dose: '0', module: 'Symptomatic' },
    { name: 'Neuropsych. Training', dose: 'NA', module: 'Other' },
    { name: 'Physiotherapy', dose: 'NA', module: 'Other' },
    { name: 'Cognitive Therapy', dose: 'NA', module: 'Other' }
];

module.exports = availableDrugs;


