const availableCountriesAndEthnicities = {
    countries: [
        { country: 'Unknown' },
        { country: 'Afghanistan' },
        { country: 'Albania' },
        { country: 'Algeria' },
        { country: 'Andorra' },
        { country: 'Angola' },
        { country: 'Anguilla' },
        { country: 'Antigua & Barbuda' },
        { country: 'Argentina' },
        { country: 'Armenia' },
        { country: 'Australia' },
        { country: 'Austria' },
        { country: 'Azerbaijan' },
        { country: 'Bahamas' },
        { country: 'Bahrain' },
        { country: 'Bangladesh' },
        { country: 'Barbados' },
        { country: 'Belarus' },
        { country: 'Belgium' },
        { country: 'Belize' },
        { country: 'Benin' },
        { country: 'Bermuda' },
        { country: 'Bhutan' },
        { country: 'Bolivia' },
        { country: 'Bosnia & Herzegovina' },
        { country: 'Botswana' },
        { country: 'Brazil' },
        { country: 'Brunei Darussalam' },
        { country: 'Bulgaria' },
        { country: 'Burkina Faso' },
        { country: 'Myanmar/Burma' },
        { country: 'Burundi' },
        { country: 'Cambodia' },
        { country: 'Cameroon' },
        { country: 'Canada' },
        { country: 'Cape Verde' },
        { country: 'Cayman Islands' },
        { country: 'Central African Republic' },
        { country: 'Chad' },
        { country: 'Chile' },
        { country: 'China' },
        { country: 'Colombia' },
        { country: 'Comoros' },
        { country: 'Congo' },
        { country: 'Costa Rica' },
        { country: 'Croatia' },
        { country: 'Cuba' },
        { country: 'Cyprus' },
        { country: 'Czech Republic' },
        { country: 'Democratic Republic of the Congo' },
        { country: 'Denmark' },
        { country: 'Djibouti' },
        { country: 'Dominica' },
        { country: 'Dominican Republic' },
        { country: 'Ecuador' },
        { country: 'Egypt' },
        { country: 'El Salvador' },
        { country: 'Equatorial Guinea' },
        { country: 'Eritrea' },
        { country: 'Estonia' },
        { country: 'Ethiopia' },
        { country: 'Fiji' },
        { country: 'Finland' },
        { country: 'France' },
        { country: 'French Guiana' },
        { country: 'Gabon' },
        { country: 'Gambia' },
        { country: 'Georgia' },
        { country: 'Germany' },
        { country: 'Ghana' },
        { country: 'Great Britain' },
        { country: 'Greece' },
        { country: 'Grenada' },
        { country: 'Guadeloupe' },
        { country: 'Guatemala' },
        { country: 'Guinea' },
        { country: 'Guinea-Bissau' },
        { country: 'Guyana' },
        { country: 'Haiti' },
        { country: 'Honduras' },
        { country: 'Hong Kong' },
        { country: 'Hungary' },
        { country: 'Iceland' },
        { country: 'India' },
        { country: 'Indonesia' },
        { country: 'Iran' },
        { country: 'Iraq' },
        { country: 'Israel and the Occupied Territories' },
        { country: 'Italy' },
        { country: 'Ivory Coast (Cote d\'Ivoire)' },
        { country: 'Jamaica' },
        { country: 'Japan' },
        { country: 'Jordan' },
        { country: 'Kazakhstan' },
        { country: 'Kenya' },
        { country: 'Kosovo' },
        { country: 'Kuwait' },
        { country: 'Kyrgyz Republic (Kyrgyzstan)' },
        { country: 'Laos' },
        { country: 'Latvia' },
        { country: 'Lebanon' },
        { country: 'Lesotho' },
        { country: 'Liberia' },
        { country: 'Libya' },
        { country: 'Liechtenstein' },
        { country: 'Lithuania' },
        { country: 'Luxembourg' },
        { country: 'Republic of Macedonia' },
        { country: 'Madagascar' },
        { country: 'Malawi' },
        { country: 'Malaysia' },
        { country: 'Maldives' },
        { country: 'Mali' },
        { country: 'Malta' },
        { country: 'Martinique' },
        { country: 'Mauritania' },
        { country: 'Mauritius' },
        { country: 'Mayotte' },
        { country: 'Mexico' },
        { country: 'Moldova' },
        { country: 'Monaco' },
        { country: 'Mongolia' },
        { country: 'Macau' },
        { country: 'Montenegro' },
        { country: 'Montserrat' },
        { country: 'Morocco' },
        { country: 'Mozambique' },
        { country: 'Namibia' },
        { country: 'Nepal' },
        { country: 'Netherlands' },
        { country: 'New Zealand' },
        { country: 'Nicaragua' },
        { country: 'Niger' },
        { country: 'Nigeria' },
        { country: 'Korea' },
        { country: 'Norway' },
        { country: 'Oman' },
        { country: 'Pacific Islands' },
        { country: 'Pakistan' },
        { country: 'Panama' },
        { country: 'Papua New Guinea' },
        { country: 'Paraguay' },
        { country: 'Peru' },
        { country: 'Philippines' },
        { country: 'Poland' },
        { country: 'Portugal' },
        { country: 'Puerto Rico' },
        { country: 'Qatar' },
        { country: 'Reunion' },
        { country: 'Romania' },
        { country: 'Russian Federation' },
        { country: 'Rwanda' },
        { country: 'Saint Kitts and Nevis' },
        { country: 'Saint Lucia' },
        { country: 'Saint Vincent\'s & Grenadines' },
        { country: 'Samoa' },
        { country: 'Sao Tome and Principe' },
        { country: 'Saudi Arabia' },
        { country: 'Senegal' },
        { country: 'Serbia' },
        { country: 'Seychelles' },
        { country: 'Sierra Leone' },
        { country: 'Singapore' },
        { country: 'Slovak Republic (Slovakia)' },
        { country: 'Slovenia' },
        { country: 'Solomon Islands' },
        { country: 'Somalia' },
        { country: 'South Africa' },
        { country: 'Korea' },
        { country: 'South Sudan' },
        { country: 'Spain' },
        { country: 'Sri Lanka' },
        { country: 'Sudan' },
        { country: 'Suriname' },
        { country: 'Swaziland' },
        { country: 'Sweden' },
        { country: 'Switzerland' },
        { country: 'Syria' },
        { country: 'Tajikistan' },
        { country: 'Taiwan' },
        { country: 'Tanzania' },
        { country: 'Thailand' },
        { country: 'Timor Leste' },
        { country: 'Togo' },
        { country: 'Trinidad & Tobago' },
        { country: 'Tunisia' },
        { country: 'Turkey' },
        { country: 'Turkmenistan' },
        { country: 'Turks & Caicos Islands' },
        { country: 'Uganda' },
        { country: 'Ukraine' },
        { country: 'United Arab Emirates' },
        { country: 'United States of America (USA)' },
        { country: 'Uruguay' },
        { country: 'Uzbekistan' },
        { country: 'Venezuela' },
        { country: 'Vietnam' },
        { country: 'Virgin Islands (UK)' },
        { country: 'Virgin Islands (US)' },
        { country: 'Yemen' },
        { country: 'Zambia' },
        { country: 'Zimbabwe' }],
    ethnicities: [
        { value: 'White' },
        { value: 'Asian' },
        { value: 'Black' },
        { value: 'Mixed/Multiple ethnic groups' },
        { value: 'Other ethnic group' },
        { value: 'Unknown' }
    ]
};

module.exports = availableCountriesAndEthnicities;