const availableFields = {
    visitFields: [
        {
            id: 1,
            definition: 'Systolic Blood Pressure',
            idname: 'visit_systolic_blood_pressure',
            section: 1,
            subsection: null,
            type: 2,
            unit: 'mmHg',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: 'SYSBP'
        },
        {
            id: 2,
            definition: 'Heart Rate',
            idname: 'visit_heart_rate',
            section: 1,
            subsection: null,
            type: 2,
            unit: 'bpm',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: 'PULSE'
        },
        {
            id: 3,
            definition: 'Diastolic Blood Pressure',
            idname: 'visit_diastolic_blood_pressure',
            section: 1,
            subsection: null,
            type: 2,
            unit: 'mmHg',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: 'DIABP'
        },
        {
            id: 4,
            definition: 'Height',
            idname: 'visit_height',
            section: 1,
            subsection: null,
            type: 2,
            unit: 'cm',
            module: 'MS',
            permittedValues: '> 0, int',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: 'HEIGHT'
        },
        {
            id: 5,
            definition: 'Weight',
            idname: 'visit_weight',
            section: 1,
            subsection: null,
            type: 2,
            unit: 'kg',
            module: 'MS',
            permittedValues: '> 0, int',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: 'WEIGHT'
        },
        {
            id: 6,
            definition: 'Percent School Attendance',
            idname: 'Percent_school_attendance',
            section: 1,
            subsection: null,
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '91-100,71-90,51-70,0-50,Unknown,NA',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 7,
            definition: 'Cognitive problems',
            idname: 'Higher_function_problem:_cognitive_problems',
            section: 2,
            subsection: 'Cognitive Functions',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 8,
            definition: 'Emotional Lability',
            idname: 'Higher_function_problem:_emotional_lability',
            section: 2,
            subsection: 'Cognitive Functions',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 9,
            definition: 'Depression',
            idname: 'Higher_function_problem:_depression',
            section: 2,
            subsection: 'Cognitive Functions',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 10,
            definition: 'Fatigue',
            idname: 'Higher_function_problem:_fatigue',
            section: 2,
            subsection: 'Cognitive Functions',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 11,
            definition: 'Seizure',
            idname: 'Higher_function_problem:_seizure',
            section: 2,
            subsection: 'Cognitive Functions',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 12,
            definition: 'Oscillopsia',
            idname: 'Cranial_nerves:_oscillopsia',
            section: 2,
            subsection: 'Cranial Nerves',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 13,
            definition: 'Vertigo',
            idname: 'Cranial_nerves:_vertigo',
            section: 2,
            subsection: 'Cranial Nerves',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 14,
            definition: 'Blurred Vision',
            idname: 'Cranial_nerves:_blurred_vision',
            section: 2,
            subsection: 'Cranial Nerves',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 15,
            definition: 'Double Vision',
            idname: 'Cranial_nerves:_double_vision',
            section: 2,
            subsection: 'Cranial Nerves',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 16,
            definition: 'Uncontrolled Eye Movements',
            idname: 'Cranial_nerves:_uncontrolled_eye_movements',
            section: 2,
            subsection: 'Cranial Nerves',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 17,
            definition: 'Dysphagia',
            idname: 'Cranial_nerves:_dysphagia',
            section: 2,
            subsection: 'Cranial Nerves',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 18,
            definition: 'Facial Weakness',
            idname: 'Cranial_nerves:_facial_weakness',
            section: 2,
            subsection: 'Cranial Nerves',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 19,
            definition: 'Greying of vision in one eye',
            idname: 'Cranial_nerves:_greying_of_vision_in_one_eye',
            section: 2,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 20,
            definition: 'Blindness in one eye',
            idname: 'Cranial_nerves:_blindness_in_one_eye',
            section: 2,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 21,
            definition: 'Facial Pain',
            idname: 'Cranial_nerves:_facial_pain',
            section: 2,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 22,
            definition: 'Field defect / Scotoma',
            idname: 'Cranial_nerves:_field_defect_/_scotoma',
            section: 2,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 23,
            definition: 'Facial Hypoesthesia',
            idname: 'Cranial_nerves:_facial_hypoesthesia',
            section: 2,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 24,
            definition: 'Difficulty walking',
            idname: 'Motor:_difficulty_walking',
            section: 2,
            subsection: 'Motor',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 25,
            definition: 'Weakness upper limbs',
            idname: 'Motor:_weakness_upper_limbs',
            section: 2,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 26,
            definition: 'weakness lower limbs',
            idname: 'Motor:_weakness_lower_limbs',
            section: 2,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 27,
            definition: 'Weakness lower limbs',
            idname: 'Motor:_weakness_lower_limbs',
            section: 2,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 28,
            definition: 'Lhermitte\'s sign',
            idname: 'Somatosensory:_Lhermitte\'s_sign',
            section: 2,
            subsection: 'Somatosensory',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 29,
            definition: 'Heat intolerance',
            idname: 'Somatosensory:_Heat_intolerance',
            section: 2,
            subsection: 'Somatosensory',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 30,
            definition: 'Pain',
            idname: 'Somatosensory:_pain',
            section: 2,
            subsection: 'Somatosensory',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 31,
            definition: 'Paresthesia',
            idname: 'Somatosensory:_paresthesia',
            section: 2,
            subsection: 'Somatosensory',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 32,
            definition: 'Dysesthesia',
            idname: 'Somatosensory:_dysesthesia',
            section: 2,
            subsection: 'Somatosensory',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 33,
            definition: 'Anesthesia',
            idname: 'Somatosensory:_anesthesia',
            section: 2,
            subsection: 'Somatosensory',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 34,
            definition: 'Pruritus',
            idname: 'Somatosensory:_pruritus',
            section: 2,
            subsection: 'Somatosensory',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 35,
            definition: 'Bladder urgency',
            idname: 'Autonomic:_bladder_urgency',
            section: 2,
            subsection: 'Autonomic',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 36,
            definition: 'Bladder frequency',
            idname: 'Autonomic:_bladder_frequency',
            section: 2,
            subsection: 'Autonomic',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 37,
            definition: 'Bladder incontinence',
            idname: 'Autonomic:_bladder_incontinence',
            section: 2,
            subsection: 'Autonomic',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 38,
            definition: 'Bladder hesitancy',
            idname: 'Autonomic:_bladder_hesitancy',
            section: 2,
            subsection: 'Autonomic',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 39,
            definition: 'Constipation',
            idname: 'Autonomic:_constipation',
            section: 2,
            subsection: 'Autonomic',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 40,
            definition: 'Bowel incontinence',
            idname: 'Autonomic:_bowel_incontinence',
            section: 2,
            subsection: 'Autonomic',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 41,
            definition: 'Problems with sexual function',
            idname: 'Autonomic:_problems_with_sexual_function',
            section: 2,
            subsection: 'Autonomic',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 42,
            definition: 'Information processing speed',
            idname: 'Higher_function_problem:_information_processing_speed',
            section: 3,
            subsection: 'Cognitive Functions',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 43,
            definition: 'Executive functions',
            idname: 'Higher_function_problem:_executive_functions',
            section: 3,
            subsection: 'Cognitive Functions',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 44,
            definition: 'Memory',
            idname: 'Higher_function_problem:_memory',
            section: 3,
            subsection: 'Cognitive Functions',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 45,
            definition: 'Verbal fluency',
            idname: 'Higher_function_problem:_verbal_fluency',
            section: 3,
            subsection: 'Cognitive Functions',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 46,
            definition: 'Seizure',
            idname: 'Higher_function_problem:_seizure',
            section: 3,
            subsection: 'Cognitive Functions',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 47,
            definition: 'Nystagmus',
            idname: 'Cranial_nerves:_nystagmus',
            section: 3,
            subsection: 'Cranial Nerves',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 48,
            definition: 'Red desaturation',
            idname: 'Cranial_nerves:_red_desaturation',
            section: 3,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 49,
            definition: 'Sixth nerve palsy',
            idname: 'Cranial_nerves:_sixth_nerve_palsy',
            section: 3,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 50,
            definition: 'Third nerve palsy',
            idname: 'Cranial_nerves:_third_nerve_palsy',
            section: 3,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 51,
            definition: 'Trigeminal neuralgia',
            idname: 'Cranial_nerves:_trigeminal_neuralgia',
            section: 3,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 52,
            definition: 'Trigeninal palsy',
            idname: 'Cranial_nerves:_trigeninal_palsy',
            section: 3,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 53,
            definition: 'Fourth nerve palsy',
            idname: 'Cranial_nerves:_fourth_nerve_palsy',
            section: 3,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 54,
            definition: 'Facial hypoesthesia',
            idname: 'Cranial_nerves:_facial_hypoesthesia',
            section: 3,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 55,
            definition: 'Hearing loss',
            idname: 'Cranial_nerves:_hearing_loss',
            section: 3,
            subsection: 'Cranial Nerves',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 56,
            definition: 'Tremor postural upper limbs',
            idname: 'Motor:_tremor_postural_upper_limbs',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 57,
            definition: 'Tremor intention upper limbs',
            idname: 'Motor:_tremor_intention_upper_limbs',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 58,
            definition: 'Spasticity upper limbs',
            idname: 'Motor:_spasticity_upper_limbs',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 59,
            definition: 'Spasticity lower limbs',
            idname: 'Motor:_spasticity_lower_limbs',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 60,
            definition: 'Tendon reflexes:hyperreflexia:biceps:right',
            idname: 'Motor:_tendon_reflexes:_hyperreflexia:_biceps_right',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '3,4',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 61,
            definition: 'Tendon reflexes:hyperreflexia:biceps:left',
            idname: 'Motor:_tendon_reflexes:_hyperreflexia:_biceps_left',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '3,4',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 62,
            definition: 'Tendon reflexes:hyperreflexia:patella:right',
            idname: 'Motor:_tendon_reflexes:_hyperreflexia:_patella_right',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '3,4',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 63,
            definition: 'Tendon reflexes:hyperreflexia:patella:left',
            idname: 'Motor:_tendon_reflexes:_hyperreflexia:_patella_left',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '3,4',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 64,
            definition: 'Tendon reflexes:hyperreflexia:ankle right',
            idname: 'Motor:_tendon_reflexes:_hyperreflexia:_ankle_right',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '3,4',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 65,
            definition: 'Tendon reflexes:hyperreflexia:ankle:left',
            idname: 'Motor:_tendon_reflexes:_hyperreflexia:_ankle_left',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '3,4',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 66,
            definition: 'Tendon reflexes:hyporeflexia:biceps:right',
            idname: 'Motor:_tendon_reflexes:_hyporeflexia:_biceps_right',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '1,2',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 67,
            definition: 'Tendon reflexes:hyporeflexia:biceps:left',
            idname: 'Motor:_tendon_reflexes:_hyporeflexia:_biceps_left',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '1,2',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 68,
            definition: 'Tendon reflexes:hyporeflexia:patella:right',
            idname: 'Motor:_tendon_reflexes:_hyporeflexia:_patella_right',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '1,2',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 69,
            definition: 'Tendon reflexes:hyporeflexia:patella:left',
            idname: 'Motor:_tendon_reflexes:_hyporeflexia:_patella_left',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '1,2',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 70,
            definition: 'Tendon reflexes:hyporeflexia:ankle:right',
            idname: 'Motor:_tendon_reflexes:_hyporeflexia:_ankle_right',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '1,2',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 71,
            definition: 'Tendon reflexes:hyporeflexia:ankle:left',
            idname: 'Motor:_tendon_reflexes:_hyporeflexia:_ankle_left',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '1,2',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 72,
            definition: 'Tendon reflexes:plantar response:right',
            idname: 'Motor:_tendon_reflexes:_plantar_response_right',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'NORMAL,ABNORMAL,UNKNOWN',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 73,
            definition: 'Tendon reflexes:plantar response:left',
            idname: 'Motor:_tendon_reflexes:_plantar_response_left',
            section: 3,
            subsection: 'Motor',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'NORMAL,ABNORMAL,UNKNOWN',
            labels: null,
            referenceType: 1, laterality: null
        },
        {
            id: 74,
            definition: 'Ataxia:upper limb',
            idname: 'Cerebellar:_Ataxia_upper_limb',
            section: 3,
            subsection: 'Cerebellar',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH,UNKNOWN',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 75,
            definition: 'Ataxia:lower limb',
            idname: 'Cerebellar:_Ataxia_lower_limb',
            section: 3,
            subsection: 'Cerebellar',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH,UNKNOWN',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 76,
            definition: 'Ataxia:trunk',
            idname: 'Cerebellar:_Ataxia_trunk',
            section: 3,
            subsection: 'Cerebellar',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LEFT,RIGHT,BOTH,UNKNOWN',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 77,
            definition: 'Problem',
            idname: 'Mobility:_problem',
            section: 3,
            subsection: 'Mobility',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'LIMITED AMBULATION,WHEELCHAIR BOUND,BEDRIDDEN,UNKNOWN',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 78,
            definition: 'Using walking aid',
            idname: 'Mobility:_using_walking_aid',
            section: 3,
            subsection: 'Mobility',
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 79,
            definition: 'Expanded Disability Status Scale (EDSS) Total',
            idname: 'Expanded_Disability_Status_Scale_EDSS_total',
            section: 4,
            subsection: 'QS',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '0,1,2,3,4,5,6,7,8,9,10',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 80,
            definition: 'Expanded Disability Status Scale (EDSS) Total Calculated',
            idname: 'Expanded_Disability_Status_Scale_EDSS_total_calculated',
            section: 4,
            subsection: 'QS',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '0,1,2,3,4,5,6,7,8,9,10',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 81,
            definition: 'Expanded Disability Status Scale (EDSS) Pyramidal',
            idname: 'Expanded_Disability_Status_Scale_EDSS_Pyramidal',
            section: 4,
            subsection: 'QS',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '0,1,2,3,4,5,6',
            labels: 'Normal,'
                + 'Abnormal signs without disability,'
                + 'Minimal disability,'
                + 'Mild or moderate paraparesis or hemiparesis (detectable weakness but most sustained for short periods, fatigue problem); severe monoparesis (almost no function),'
                + 'Marked paraparesis or hemiparesis (functions difficult); moderate quadriparesis (function decreased but can be sustained for short periods); or monoplegia,'
                + 'Paraplegia, hemiplegia or marked quadriparesis,'
                + 'Quadriplegia',
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 82,
            definition: 'Expanded Disability Status Scale (EDSS) Cerebellar',
            idname: 'Expanded_Disability_Status_Scale_EDSS_Cerebellar',
            section: 4,
            subsection: 'QS',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '0,1,2,3,4,5',
            labels: 'Normal,'
                + 'Abnormal signs without disability,'
                + 'Mild ataxia,'
                + 'Moderate truncal or limb ataxia (tremor or clumsy movements interfere with function in all spheres),'
                + 'Severe ataxia in all limbs (most function is very difficult),'
                + 'Unable to perform coordinated movements due to ataxia',
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 83,
            definition: 'Expanded Disability Status Scale (EDSS) Brain Stem',
            idname: 'Expanded_Disability_Status_Scale_EDSS_Brain_Stem',
            section: 4,
            subsection: 'QS',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '0,1,2,3,4,5',
            labels: 'Normal'
                + 'Signs only,'
                + 'Moderate nystagmus or other mild disability,'
                + 'Severe nystagmus, marked extraocular weakness or moderate disability of other cranial nerves,'
                + 'Marked dysarthria or other marked disability,'
                + 'Inability to swallow or speak',
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 84,
            definition: 'Expanded Disability Status Scale (EDSS) Sensory',
            idname: 'Expanded_Disability_Status_Scale_EDSS_Sensory',
            section: 4,
            subsection: 'QS',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '0,1,2,3,4,5,6',
            labels: 'Normal,'
                + 'Vibration or figure-writing decreased, only in one or two limbs,'
                + 'Mild decrease in touch or pain or position sense, and/or moderate decrease in vibration in one or two limbs; or vibration decrease alone in three or four limbs,'
                + 'Moderate decrease in touch or pain or position sense, and/or essentially lost vibration in one or two limbs; or mild decrease in touch or pain and/or moderate decrease in all proprioceptive test in three or four limbs,'
                + 'Marked decrease in touch or pain or lost proprioception, alone or combined, in one or two limbs; or moderate decrease in touch or pain and/or severe proprioceptive decrease in more then two limbs,'
                + 'Lost of sensation in one or two limbs; or proprioception for most of the body below the head,'
                + 'Sensation essentially lost below the head',
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 85,
            definition: 'Expanded Disability Status Scale (EDSS) Bowel Bladder',
            idname: 'Expanded_Disability_Status_Scale_EDSS_Bowel_Bladder',
            section: 4,
            subsection: 'QS',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '0,1,2,3,4,5,6',
            labels: 'Normal,'
                + 'Mild urinary hesitancy, urgency or retention,'
                + 'Moderate hesitancy, urgency, retention of bowel or bladder, or rare urinary incontinence (intermittent self-catheterisation, manual compression to evacuate bladder or finger evacuation or stool),'
                + 'Frequent urinary incontinence,'
                + 'In need of regular intermittent catheterisation (and constant use of measures to evacuate stools),'
                + 'In dwelling catheter,'
                + 'Loss of bowel and/or bladder function,',
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 86,
            definition: 'Expanded Disability Status Scale (EDSS) Visual',
            idname: 'Expanded_Disability_Status_Scale_EDSS_Bowel_Visual',
            section: 4,
            subsection: 'QS',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '0,1,2,3,4,5,6',
            labels: 'Normal,'
                + 'Scotoma with visual acuity (corrected) better then 6/9,'
                + 'Worse eye with maximal visual acuity (corrected) of 6/9 to 6/12,'
                + 'Worse eye with maximal visual acuity (corrected) of 6/18 to 6/24,'
                + 'Worse eye with maximal visual acuity (corrected) of 6/36 to 6/60. Or grade three plus maximal acuity of better eye of 6/18 or less,'
                + 'Worse eye with maximal visual acuity (corrected) of 6/60. Or grade four plus maximal visual acuity of better eye of 6/18 or less,'
                + 'Grade 5 plus maximal visual acuity of better eye worse then 6/18',
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 87,
            definition: 'Expanded Disability Status Scale (EDSS) Mental',
            idname: 'Expanded_Disability_Status_Scale_EDSS_Mental',
            section: 4,
            subsection: 'QS',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '0,1,2,3,4,5',
            labels: 'Normal,'
                + 'Mood alteration only- fatigue not intefering with daily activity (does not affect EDSS score,),'
                + 'Mild decrease in mentation- fatigue intefering with daily activity,'
                + 'Moderate decrease in mentation,'
                + 'Marked decrease in mentation (chronic brain syndrome - moderate),'
                + 'Dementia or chronic brain syndrome - severe or incompetent',
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 88,
            definition: 'Expanded Disability Status Scale (EDSS) Ambulation',
            idname: 'Expanded_Disability_Status_Scale_EDSS_Ambulation',
            section: 4,
            subsection: 'QS',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '0,1,2,3,4,5,6,7,8,9,10,11,12',
            labels: 'Fully ambulatory,'
                + '500 m without aid/rest,'
                + '300 m without aid/rest,'
                + '200 m without aid/rest,'
                + '100 m without aid/rest,'
                + '100 m with unilateral assistance,'
                + '200 m with bilateral assistance,'
                + 'Essentially restricted to wheelchair (wheels self),'
                + 'Restricted to wheelchair (may need help in transfer),'
                + 'Essentially restricted to bed/chair,'
                + 'Restricted to bed much of day,'
                + 'Bed patient. Can communicate and eat,'
                + 'Helpless bed patient. Unable to communicate/eat/swallow',
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 89,
            definition: 'EDMUS',
            idname: 'EDMUS',
            section: 4,
            subsection: 'QS',
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: '0,1,2,3,4,5,6A,6B,7,8,9,10',
            labels: 'Normal findings on neurological examination.,'
                + 'No disability. Minimal signs on neurological examination.,'
                + 'Minimal and not ambulation-related disability. Able to run.,'
                + 'Unlimited walking distance (WD) without rest but unable to run; or a significant not ambulation-related disability.,'
                + 'Walks without aid. Limited WD but > 500 meters without rest.,'
                + 'Walks without aid. Limited WD- < 500 meters without rest.,'
                + 'Walks with permanent unilateral support. WD < 100 meters without rest.,'
                + 'Walks with permanent bilateral support. WD < 100 meters without rest.,'
                + 'Home restricted. A few steps with wall or furniture assistance. WD < 20 meters without rest.,'
                + 'Chair restricted. Unable to take a step. Some effective use of arms.,'
                + 'Bedridden and totally helpless.,'
                + 'Death due to MS.',
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 90,
            definition: '25 feet walk test:trial n°1',
            idname: '25_feet_walk_test_first_try',
            section: 4,
            subsection: 'FT',
            type: 2,
            unit: 'sec',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 91,
            definition: '25 feet walk test:trial n°2',
            idname: '25_feet_walk_test_second_try',
            section: 4,
            subsection: 'FT',
            type: 2,
            unit: 'sec',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 92,
            definition: 'Nine hole peg test:left:trial n°1',
            idname: 'Nine_hole_peg_test:_left:_first_try',
            section: 4,
            subsection: 'FT',
            type: 2,
            unit: 'sec',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 93,
            definition: 'Nine hole peg test:left:trial n°2',
            idname: 'Nine_hole_peg_test:_left:_second_try',
            section: 4,
            subsection: 'FT',
            type: 2,
            unit: 'sec',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 94,
            definition: 'Nine hole peg test:right:trial n°1',
            idname: 'Nine_hole_peg_test:_right:_first_try',
            section: 4,
            subsection: 'FT',
            type: 2,
            unit: 'sec',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 95,
            definition: 'Nine hole peg test:right:trial n°2',
            idname: 'Nine_hole_peg_test:_right:_second_try',
            section: 4,
            subsection: 'FT',
            type: 2,
            unit: 'sec',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 96,
            definition: 'Low contrast letter acuity:left ',
            idname: 'Low_contrast_letter_acuity:_left_',
            section: 4,
            subsection: 'VisualAcuity',
            type: 2,
            unit: '/20',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: 'LEFT',
            cdiscName: null
        },
        {
            id: 97,
            definition: 'Low contrast letter acuity:right',
            idname: 'Low_contrast_letter_acuity:_right',
            section: 4,
            subsection: 'VisualAcuity',
            type: 2,
            unit: '/20',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: 'RIGHT',
            cdiscName: null
        },
        {
            id: 98,
            definition: 'Symbol Digit Modality Test',
            idname: 'symbol_digit_modality_test',
            section: 4,
            subsection: 'FT',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        }
    ],
    testFields: [
        {
            id: 1,
            definition: 'ANA',
            idname: 'ANA',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 2,
            definition: 'ANCA',
            idname: 'ANCA',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 3,
            definition: 'Anti-cardiolipin',
            idname: 'Anti-cardiolipin',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 4,
            definition: 'Anti-DNA',
            idname: 'Anti-DNA',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 5,
            definition: 'Anti-HCV antibody',
            idname: 'Anti-HCV_antibody',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 6,
            definition: 'Anti-HIV antibody',
            idname: 'Anti-HIV_antibody',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 7,
            definition: 'Anti-LKM',
            idname: 'Anti-LKM',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 8,
            definition: 'Anti-mitochondrial',
            idname: 'Anti-mitochondrial',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 9,
            definition: 'Anti-parietal cell antibodies',
            idname: 'Anti-parietal_cell_antibodies',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 10,
            definition: 'Anti-Ro',
            idname: 'Anti-Ro',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 11,
            definition: 'Anti-smooth muscle',
            idname: 'Anti-smooth_muscle',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 12,
            definition: 'Anti-transglutaminase',
            idname: 'Anti-transglutaminase',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 13,
            definition: 'Anti-varicella',
            idname: 'Anti-varicella',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 14,
            definition: 'AQP4',
            idname: 'AQP4',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 15,
            definition: 'GlyR',
            idname: 'GlyR',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 16,
            definition: 'HBV surface antigen',
            idname: 'HBV_surface_antigen',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 17,
            definition: 'Hepatitis A',
            idname: 'hepatitis_A',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 18,
            definition: 'Hepatitis B',
            idname: 'hepatitis_B',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 19,
            definition: 'Hepatitis C',
            idname: 'hepatitis_C',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 20,
            definition: 'Jo1',
            idname: 'Jo1',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 21,
            definition: 'LA',
            idname: 'LA',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 22,
            definition: 'LUPUS anti-coagulant',
            idname: 'LUPUS_anti-coagulant',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 23,
            definition: 'MOG',
            idname: 'MOG',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 24,
            definition: 'Neutralising Anti-IFN antibody',
            idname: 'Neutralising_Anti-IFN_antibody',
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null, labels: null,
            referenceType: 1,
            laterality: null, cdiscName: null
        },
        {
            id: 25,
            definition: 'Neutralising Anti-natalizumab antibody',
            idname: 'Neutralising_Anti-natalizumab_antibody',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 26,
            definition: 'NMDAR',
            idname: 'NMDAR',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 27,
            definition: 'NMO IgG',
            idname: 'NMO_IgG',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 28,
            definition: 'Plasma anti-JC virus',
            idname: 'Plasma_anti-JC_virus',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 29,
            definition: 'RNP',
            idname: 'RNP',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 30,
            definition: 'Scl70',
            idname: 'Scl70',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 31,
            definition: 'SM',
            idname: 'SM',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 32,
            definition: 'P100 Left:Abnormal',
            idname: 'P100_Left:_Abnormal',
            section: null,
            subsection: null,
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 2,
            laterality: 'LEFT',
            cdiscName: 'P100 Interpretation'
        },
        {
            id: 33,
            definition: 'P100 Left:Amplitude',
            idname: 'P100_Left:_amplitude',
            section: null,
            subsection: null,
            type: 1,
            unit: 'uV',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 2,
            laterality: 'LEFT',
            cdiscName: 'P100 Amplitude'
        },
        {
            id: 34,
            definition: 'P100 Left:P100 latency',
            idname: 'P100_Left:_P100_latency',
            section: null,
            subsection: null,
            type: 1,
            unit: 'msec',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 2,
            laterality: 'LEFT',
            cdiscName: 'P100 Latency'
        },
        {
            id: 35,
            definition: 'P100 right:Abnormal',
            idname: 'P100_right:_Abnormal',
            section: null,
            subsection: null,
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 2,
            laterality: 'RIGHT',
            cdiscName: 'P100 Interpretation'
        },
        {
            id: 36,
            definition: 'P100 right:Amplitude',
            idname: 'P100_right:_amplitude',
            section: null,
            subsection: null,
            type: 1,
            unit: 'uV',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 2,
            laterality: 'RIGHT',
            cdiscName: 'P100 Amplitude'
        },
        {
            id: 37,
            definition: 'P100 right:P100 latency',
            idname: 'P100_right:_P100_latency',
            section: null,
            subsection: null,
            type: 1,
            unit: 'msec',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 2,
            laterality: 'RIGHT',
            cdiscName: 'P100 Latency'
        },
        {
            id: 38,
            definition: 'SEP left:Upper extremity:Abnormal',
            idname: 'SEP_left:_upper_extremity:_abnormal',
            section: null,
            subsection: null,
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 2,
            laterality: 'LEFT',
            cdiscName: 'SEP Upper Extremity'
        },
        {
            id: 39,
            definition: 'SEP left:Lower extremity:Abnormal',
            idname: 'SEP_left:_lower_extremity:_abnormal',
            section: null,
            subsection: null,
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 2,
            laterality: 'LEFT',
            cdiscName: 'SEP Lower Extremity'
        },
        {
            id: 40,
            definition: 'SEP right:Upper extremity:Abnormal',
            idname: 'SEP_right:_upper_extremity:_abnormal',
            section: null,
            subsection: null,
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 2,
            laterality: 'RIGHT',
            cdiscName: 'SEP Upper Extremity'
        },
        {
            id: 41,
            definition: 'SEP right:Lower extremity:Abnormal',
            idname: 'SEP_right:_lower_extremity:_abnormal',
            section: null,
            subsection: null,
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 2,
            laterality: 'RIGHT',
            cdiscName: 'SEP Lower Extremity'
        },
        {
            id: 42,
            definition: 'Session Name',
            idname: 'Session_Name',
            section: null,
            subsection: null,
            type: 4,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 3,
            laterality: null,
            cdiscName: null
        },
        {
            id: 43,
            definition: 'Scans',
            idname: 'Scans',
            section: null,
            subsection: null,
            type: 6,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 3,
            laterality: null,
            cdiscName: null
        },
        {
            id: 44,
            definition: 'Scan type',
            idname: 'scan_type',
            section: null,
            subsection: null,
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'T1,T2',
            labels: null,
            referenceType: 3,
            laterality: null,
            cdiscName: null
        },
        {
            id: 45,
            definition: 'Region',
            idname: 'Morphology:_region',
            section: null,
            subsection: null,
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'BRAIN,SPINE',
            labels: null,
            referenceType: 3,
            laterality: null,
            cdiscName: null
        },
        {
            id: 46,
            definition: 'T1 Hypointense lesions',
            idname: 'Morphology:_T1_hypointense_lesions',
            section: null,
            subsection: null,
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'NEGATIVE,POSITIVE,NOT REPORTED',
            labels: null,
            referenceType: 3,
            laterality: null,
            cdiscName: null
        },
        {
            id: 47,
            definition: 'T2 Hyperintense lesions count',
            idname: 'Morphology:_T2_hyperintense_lesions_count',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 3,
            laterality: null,
            cdiscName: null
        },
        {
            id: 48,
            definition: 'T2 Hyperintense lesions volume',
            idname: 'Morphology:_T2_hyperintense_lesions_volume',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 3,
            laterality: null,
            cdiscName: null
        },
        {
            id: 49,
            definition: 'Gd enhancing lesions',
            idname: 'Morphology:_Gd_enhancing_lesions',
            section: null,
            subsection: null,
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'NONE,SINGLE,MULTIPLE,UNKNOWN',
            labels: null,
            referenceType: 3,
            laterality: null,
            cdiscName: null
        },
        {
            id: 50,
            definition: 'Gd enhancing lesions volume',
            idname: 'Morphology:_Gd_enhancing_lesions_volume',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 3,
            laterality: null,
            cdiscName: null
        },
        {
            id: 51,
            definition: 'Summary',
            idname: 'Summary',
            section: null,
            subsection: null,
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'NORMAL,TRAUMATIC,ABNORMAL MS-TYPICAL,ABNORMAL MS-ATYPICAL',
            labels: null,
            referenceType: 4,
            laterality: null,
            cdiscName: null
        },
        {
            id: 52,
            definition: 'Total protein',
            idname: 'Total-protein',
            section: null,
            subsection: null,
            type: 2,
            unit: 'mg/L',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 4,
            laterality: null,
            cdiscName: null
        },
        {
            id: 53,
            definition: 'Glucose',
            idname: 'Glucose',
            section: null,
            subsection: null,
            type: 2,
            unit: 'mg/L',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 4,
            laterality: null,
            cdiscName: null
        },
        {
            id: 54,
            definition: 'Q Albumin',
            idname: 'Q_Albumin',
            section: null,
            subsection: null,
            type: 2,
            unit: 'mg/L',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 4,
            laterality: null,
            cdiscName: null
        },
        {
            id: 55,
            definition: 'IgG',
            idname: 'IgG',
            section: null,
            subsection: null,
            type: 2,
            unit: 'mg/L',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 4,
            laterality: null,
            cdiscName: null
        },
        {
            id: 56,
            definition: 'Albumin',
            idname: 'Albumin',
            section: null,
            subsection: null,
            type: 2,
            unit: 'mg/L',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 4,
            laterality: null,
            cdiscName: null
        },
        {
            id: 57,
            definition: 'IgG index',
            idname: 'IgG_index',
            section: null,
            subsection: null,
            type: 2,
            unit: 'mg/L',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 4,
            laterality: null,
            cdiscName: null
        },
        {
            id: 58,
            definition: 'WCC',
            idname: 'WCC',
            section: null,
            subsection: null,
            type: 2,
            unit: 'mg/L',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 4,
            laterality: null,
            cdiscName: null
        },
        {
            id: 59,
            definition: 'Lymphocytes',
            idname: 'Lymphocytes',
            section: null,
            subsection: null,
            type: 2,
            unit: 'mg/L',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 4,
            laterality: null,
            cdiscName: null
        },
        {
            id: 60,
            definition: 'Oligoclonal Bands in CSF',
            idname: 'Oligoclonal_Bands_in_CSF',
            section: null,
            subsection: null,
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'TEST NOT DONE,NOT DETECTED,DETECTED,UNKNOWN',
            labels: null,
            referenceType: 4,
            laterality: null,
            cdiscName: null
        },
        {
            id: 61,
            definition: 'ALT (Alanine Aminotransferase) Test',
            idname: 'ALT_Alanine_Aminotransferase_Test',
            section: null,
            subsection: null,
            type: 2,
            unit: 'Units/Liter',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 62,
            definition: 'AST (Aspartate Aminotransferase) Test',
            idname: 'AST_Aspartate_Aminotransferase_Test',
            section: null,
            subsection: null,
            type: 2,
            unit: 'Units/Liter',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 63,
            definition: 'GGT (Gamma-Glutamyl Transpeptidase) Test',
            idname: 'GGT_Gamma_Glutamyl_Transpeptidase_Test',
            section: null,
            subsection: null,
            type: 2,
            unit: 'Units/Liter',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 64,
            definition: 'Total WBC',
            idname: 'Total_WBC',
            section: null,
            subsection: null,
            type: 2,
            unit: 'mcL',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 65,
            definition: 'Bilirubin',
            idname: 'Bilirubin',
            section: null,
            subsection: null,
            type: 2,
            unit: 'mg/dL',
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        }
    ],
    ceFields: [
        {
            id: 1,
            definition: 'Functional system affected:Pyramidal Tract',
            idname: 'Functional_system_affected_pyramidal_tract',
            section: 'Functional system affected',
            subsection: null,
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 2,
            definition: 'Functional system affected:Cerebellum',
            idname: 'Functional_system_affected_cerebellum',
            section: 'Functional system affected',
            subsection: null,
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 3,
            definition: 'Functional system affected:Brain Stem',
            idname: 'Functional_system_affected_Brain_Stem',
            section: 'Functional system affected',
            subsection: null,
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 4,
            definition: 'Functional system affected:Sensory',
            idname: 'Functional_system_affected_Sensory',
            section: 'Functional system affected',
            subsection: null,
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 5,
            definition: 'Functional system affected:Bowel/Bladder',
            idname: 'Functional_system_affected_Bowel_Bladder',
            section: 'Functional system affected',
            subsection: null,
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 6,
            definition: 'Functional system affected:Visual',
            idname: 'Functional_system_affected_Visual',
            section: 'Functional system affected',
            subsection: null,
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 7,
            definition: 'Functional system affected:Cognition',
            idname: 'Functional_system_affected_Cognition',
            section: 'Functional system affected',
            subsection: null,
            type: 5,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 8,
            definition: 'Duration',
            idname: 'Duration',
            section: null,
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 9,
            definition: 'Severity',
            idname: 'Severity',
            section: null,
            subsection: null,
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'Mild,Moderate,Severe,Unknown',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 10,
            definition: 'Recovery',
            idname: 'Recovery',
            section: null,
            subsection: null,
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'Complete,Partial,None,Unknown',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 11,
            definition: 'Impact on ADL',
            idname: 'Impact_On_ADL',
            section: null,
            subsection: null,
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'Yes,No,Unknown',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 12,
            definition: 'Steroids use',
            idname: 'Steroids',
            section: null,
            subsection: null,
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'Yes,No,Unknown',
            labels: null,
            referenceType: 1,
            laterality: null,
            cdiscName: null
        },
        {
            id: 13,
            definition: 'Infection Classification',
            idname: 'Infection_Classification',
            section: 'Classification',
            subsection: null,
            type: 3,
            unit: null,
            module: 'MS',
            permittedValues: 'UTI,Bronchitis,Sinusitis,Gastroenteritis,Tinea Infection,Sepsis,Bacterial,Viral,Abscess,Other,Unknown',
            labels: null,
            referenceType: 2,
            laterality: null,
            cdiscName: null
        },
        {
            id: 14,
            definition: 'Date of onset',
            idname: 'Date_Of_Onset',
            section: null,
            subsection: null,
            type: 4,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 2,
            laterality: null,
            cdiscName: null
        },
        {
            id: 15,
            definition: 'Date of resolution',
            idname: 'Date_Of_Resolution',
            section: null,
            subsection: null,
            type: 4,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 2,
            laterality: null,
            cdiscName: null
        },
        {
            id: 16,
            definition: 'Date of hospitalisation',
            idname: 'Date_Of_Hospitalisation',
            section: null,
            subsection: null,
            type: 4,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 2,
            laterality: null,
            cdiscName: null
        },
        {
            id: 17,
            definition: 'Date of discharge',
            idname: 'Date_Of_Discharge',
            section: null,
            subsection: null,
            type: 4,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 2,
            laterality: null,
            cdiscName: null
        },
        {
            id: 18,
            definition: 'Comments - Elaboration',
            idname: 'Comments_Elaboration_Infection',
            section: null,
            subsection: null,
            type: 4,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 2,
            laterality: null,
            cdiscName: null
        },
        {
            id: 19,
            definition: 'Opportunistic Infection Classification',
            idname: 'Opportunistic_Infection_Classification',
            section: 'Classification',
            subsection: null,
            type: 2,
            unit: null,
            module: 'MS',
            permittedValues: 'PML,Herpes Zoster,Herpes Simplex,Varicella,Viral Hepatitis,Bacterial infection- listeria,Other infection,Mycosis,Abscess,Other,Unknown',
            labels: null,
            referenceType: 3,
            laterality: null,
            cdiscName: null
        },
        {
            id: 20,
            definition: 'Date of onset',
            idname: 'Date_Of_Onset_opportunistic',
            section: null,
            subsection: null,
            type: 4,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 3,
            laterality: null,
            cdiscName: null
        },
        {
            id: 21,
            definition: 'Date of resolution',
            idname: 'Date_Of_Resolution_opportunistic',
            section: null,
            subsection: null,
            type: 4,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 3,
            laterality: null,
            cdiscName: null
        },
        {
            id: 22,
            definition: 'Comments - Elaboration',
            idname: 'Comments_Elaboration_Opportunistic_Infection',
            section: null,
            subsection: null,
            type: 4,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 3,
            laterality: null,
            cdiscName: null
        },
        {
            id: 23,
            definition: 'Primary and underlying cause of death',
            idname: 'Primary_and_underlying_cause_of_death',
            section: null,
            subsection: null,
            type: 4,
            unit: null,
            module: 'MS',
            permittedValues: null,
            labels: null,
            referenceType: 4,
            laterality: null,
            cdiscName: null
        }
    ]
};

module.exports = availableFields;
