export default {
    login: {
        LOGIN_REQUESTED: 'LOGIN_REQUESTED',
        LOGIN_SUCCESS: 'LOGIN_SUCCESS',
        LOGIN_FAILURE: 'LOGIN_FAILURE'
    },
    searchPatientById: {
        SEARCH_PATIENTS_BY_ID_REQUEST: 'SEARCH_PATIENTS_BY_ID_REQUEST',
        SEARCH_RESULT_BY_ID_SUCCESS: 'SEARCH_RESULT_BY_ID_SUCCESS'
    },
    patientProfile: {
        
    },
    visits: {
        CREATE_VISIT_REQUEST: 'CREATE_VISIT_REQUEST',
        CREATE_VISIT_SUCCESS: 'CREATE_VISIT_SUCCESS'
    },
    tests: {
        CREATE_TEST_REQUEST: 'CREATE_TEST_REQUEST',
        CREATE_TEST_SUCCESS: 'CREATE_TEST_SUCCESS'
    },
    treatments: {
        CREATE_TREATMENT_REQUEST: 'CREATE_TREATMENT_REQUEST',
        CREATE_TREATMENT_SUCCESS: 'CREATE_TREATMENT_SUCCESS'
    },
    clinicalEvents: {
        CREATE_CE_REQUEST: 'CREATE_CE_REQUEST',
        CREATE_CE_SUCCESS: 'CREATE_CE_SUCCESS'
    },
    data: {
        ALTER_DATA_REQUEST: 'ALTER_DATA_REQUEST',
        ALTER_DATA_SUCCESS: 'ALTER_DATA_SUCCESS',
        ALTER_DATA_FAILURE: 'ALTER_DATA_FAILURE'
    },
    availableFields: {
        GET_DEMO_FIELDS_SUCCESS: 'GET_DEMO_FIELDS_SUCCESS',
        GET_VISIT_FIELDS_SUCCESS: 'GET_VISIT_FIELDS_SUCCESS',
        GET_TEST_FIELDS_SUCCESS: 'GET_TEST_FIELDS_SUCCESS',
        GET_CE_TYPES_SUCCESS: 'GET_CE_TYPES_SUCCESS',
        GET_TEST_TYPES_SUCCESS: 'GET_TEST_TYPES_SUCCESS',
        GET_DRUGS_SUCCESS: 'GET_DRUGS_SUCCESS',
        GET_INPUT_TYPES_SUCCESS: 'GET_INPUT_TYPES_SUCCESS'
    }
}