export default {
    patientProfile: {
        
    },
    visits: {
        CREATE_VISIT_REQUEST: 'CREATE_VISIT_REQUEST',
        CREATE_VISIT_SUCCESS: 'CREATE_VISIT_SUCCESS'
    },
    tests: {
        CREATE_TEST_REQUEST: 'CREATE_TEST_REQUEST',
        CREATE_TEST_SUCCESS: 'CREATE_TEST_SUCCESS'
    },
    treatments: {
        CREATE_TREATMENT_REQUEST: 'CREATE_TREATMENT_REQUEST',
        CREATE_TREATMENT_SUCCESS: 'CREATE_TREATMENT_SUCCESS'
    },
    clinicalEvents: {
        CREATE_CE_REQUEST: 'CREATE_CE_REQUEST',
        CREATE_CE_SUCCESS: 'CREATE_CE_SUCCESS'
    },
    data: {
        ALTER_DATA_REQUEST: 'ALTER_DATA_REQUEST',
        ALTER_DATA_SUCCESS: 'ALTER_DATA_SUCCESS',
        ALTER_DATA_FAILURE: 'ALTER_DATA_FAILURE'
    }
}